# 用作需要稳定支持的环境
# php5.6

FROM php:5.6-fpm
MAINTAINER XiaodongHuang <ddonng@qq.com>

EXPOSE 9000

RUN apt-get update && apt-get install -y git
# install pdo_mysql extension
RUN docker-php-ext-install pdo_mysql

# memcached extensions
RUN apt-get update \
  && apt-get install -y libmemcached11 libmemcachedutil2 build-essential libmemcached-dev libz-dev \
  && pecl install memcached \
  && echo extension=memcached.so >> /usr/local/etc/php/conf.d/memcached.ini

# install phpredis extension
ENV PHPREDIS_VERSION 2.2.8

RUN curl -L -o /tmp/redis.tar.gz https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz \
    && tar xfz /tmp/redis.tar.gz \
    && rm -r /tmp/redis.tar.gz \
    && mv phpredis-$PHPREDIS_VERSION /usr/src/php/ext/redis \
    && docker-php-ext-install redis

# install mongo extension
RUN apt-get -y install libssl-dev pkg-config && pecl install mongo \
    && echo "extension=mongo.so" > /usr/local/etc/php/conf.d/mongo.ini

# swoole extension
RUN pecl install swoole && echo extension=swoole.so >> /usr/local/etc/php/conf.d/swoole.ini

# phalcon extension
RUN git clone http://github.com/phalcon/cphalcon
RUN cd cphalcon/build && ./install \
    && echo extension=phalcon.so >> /usr/local/etc/php/conf.d/phalcon.ini \
    && cd ../ && rm -rf cphalcon

# clean
RUN apt-get remove -y build-essential libmemcached-dev libz-dev \
    && apt-get autoremove -y

RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
